TriggerConfig = {}

TriggerConfig.LimitedTriggers = {
	{trigger = '_chat:messageEntered', limit = 10},
	{trigger = 'esx_sheriffjob:givehandcuff', limit = 4},
	{trigger = 'esx-qalle-jail:jailPlayer', limit = 4},
	{trigger = 'esx_sheriffjob:requestarrest', limit = 4},
	{trigger = 'esx_boatshop:buyVehicle', limit = 3},
	{trigger = 'InteractSound_SV:PlayOnAl', limit = 100},
	{trigger = 'qb-multicharacter:server:deleteCharacter', limit = 3},
	{trigger = 'esx_communityservice:sendToCommunityService', limit = 3},
	{trigger = 'esx_sheriffjob:message', limit = 5},
	{trigger = 'esx_sheriffjob:OutVehicle', limit = 5},
	{trigger = 'esx_sheriffjob:putInVehicle', limit = 5},
	{trigger = 'esx_sheriffjob:drag', limit = 5},
	{trigger = 'esx_sheriffjob:handcuff', limit = 5},
	{trigger = 'esx_policejob:givehandcuff', limit = 5},
	{trigger = 'esx_policejob:message', limit = 5},
	{trigger = 'esx_policejob:drag', limit = 5},
	{trigger = 'esx_policejob:handcuff', limit = 4},
   {trigger = 'tgiann-kelepce:polis-kelepce-tak-takilan', limit = 5},
	{trigger = 'tgiann-kelepce:kelepce-tak-takilan', limit = 5},
	{trigger = 'bank:withdraw', limit = 5},
	{trigger = 'esx_uber:pay', limit = 5},
	{trigger = 'qb-phone:server:AddAdvert', limit = 6},
	{trigger = 'qb-phone:saveTwitterToDatabase', limit = 6},
	{trigger = 'gcPhone:sendMessage', limit = 20},
	{trigger = 'esx_billing:sendBill', limit = 5},
	{trigger = 'esx_vehicleshop:setVehicleOwnedPlayerId', limit = 4},
	{trigger = 'esx_cartesim:sim_delete', limit = 4},
	{trigger = 'esx_handcuffs:cuffing', limit = 4},
	{trigger = 'police:cuffGranted', limit = 4},
	{trigger = 'esx_policejob:spawned', limit = 4},
	{trigger = 'utk_fh:rewardCash', limit = 30},
	{trigger = 'utk_oh:rewardCash', limit = 30},
	{trigger = 'cmg2_animationsCarry:sync', limit = 4},
	{trigger = 'ServerValidEmote', limit = 5},
   
}

TriggerConfig.AntiJobTriggers = {
	{trigger = "esx_policejob:handcuff", job = "police"},
	{trigger = "esx_policejob:drag", job = "police"},
	{trigger = "esx_policejob:requestrelease", job = "police"},
	{trigger = "esx_policejob:givehandcuff", job = "police"},
	{trigger = "esx_sheriffjob:handcuff", job = "sheriff"},
	{trigger = "esx_sheriffjob:drag", job = "sheriff"},
	{trigger = "esx_sheriffjob:givehandcuff", job = "sheriff"},
	{trigger = "esx_sheriffjob:requestarrest", job = "sheriff"},
	{trigger = "esx_sheriffjob:message", job = "sheriff"},
	{trigger = "esx-qalle-jail:jailPlayer", job = "police"},
	{trigger = "tgiann-kelepce:polis-kelepce-tak-takilan", job = "police"},
}

TriggerConfig.ProtectandValuedEvents = { 
	{trigger = "esx_fueldelivery:pay", value = 1000},
	{trigger = "esx_carthief:pay", value = 1000},
	{trigger = "esx_godirtyjob:pay", value = 1000},
	{trigger = "esx_pizza:pay", value = 1000},
	{trigger = "esx_ranger:pay", value = 1000},
	{trigger = "esx_taxijob:success", value = 10000},
	{trigger = "esx_garbagejob:pay", value = 1000},
	{trigger = "esx_gopostaljob:pay", value = 1000},
	{trigger = "esx_slotmachine:sv:2", value = 1000},
	{trigger = "esx_dmvschool:pay", value = 10000},
	{trigger = "esx_tankerjob:pay", value = 10000},
	{trigger = "esx_uber:pay", value = 2400},
   {trigger = "AdminMenu:giveBank", value = 10000},
	{trigger = "AdminMenu:giveCash", value = 10000},
	{trigger = "LegacyFuel:PayFuel", value = 10000},
	{trigger = "esx_society:billing", value = 100000},
	{trigger = "bank:withdraw", value = 160000000},
	{trigger = "bank:deposit", value = 160000000},
   {trigger = 't1ger_mechanicjob:JobReward', value = 2000000},
	{trigger = 'esx_kazikazan:withdraw', value = 2000000},
	{trigger = 'sametk:hapispara', value = 40000},
	{trigger = 't1ger_deliveryjob:retrievePaycheck', value = 90000000},
}

TriggerConfig.ProtecedEvents = { 
	{trigger = "esx_communityservicesex:sendToCommunityService", value = -1},
	{trigger = "CarryPeople:sync", value = -1},
	{trigger = "esx_kekke_tackle:tryTackle", value = -1},
	{trigger = "esx_policejob:handcuff", value = -1},
	{trigger = "esx_policejob:drag", value = -1},
	{trigger = "esx_sheriffjob:drag", value = -1},
	{trigger = "esx_policejob:putInVehicle", value = -1},
	{trigger = "esx_sheriffjob:handcuff", value = -1},
	{trigger = "esx_sheriffjob:putInVehicle", value = -1},
	{trigger = "js:jailuser", value = -1},
	{trigger = "esx_jail:sendToJail", value = -1},
	{trigger = "esx_jailer:sendToJail", value = -1}, 
	{trigger = "esx-qalle-jail:jailPlayer", value = -1},
	{trigger = "esx_communityservice:sendToCommunityService", value = -1},
	{trigger = "3c98dea34ba8c14eea839a5d9b6e5d15:jailPlayer", value = -1},
	{trigger = 't1ger_mechanicjob:JobReward', value = -1},
	{trigger = 'fonzillo', value = -1},
	{trigger = 'deep_hacker:giveMoney', value = -1},
	{trigger = 'esx_kazikazan:withdraw', value = -1},
	{trigger = 'sametk:hapispara', value = -1},
	{trigger = 't1ger_deliveryjob:retrievePaycheck', value = -1},
	{trigger = 'wiro_miner:paraver', value = -1},
	{trigger = 'edz-cashdeskrob:giveMoney', value = -1},
	{trigger = 'esx-chopshop:addCash', value = -1},
	{trigger = 'houseRobberies:giveMoney', value = -1},
	{trigger = 'm3:shoprobbery:giveMoney', value = -1},
	{trigger = 'utk_fh:rewardCash', value = -1},
	{trigger = 'utk_oh:rewardCash', value = -1},
	{trigger = 'wiro_miner:paraver', value = -1},
	{trigger = 'edz-cashdeskrob:giveMoney', value = -1},
	{trigger = 'esx-chopshop:addCash', value = -1},
	{trigger = 'houseRobberies:giveMoney', value = -1},
	{trigger = 'utk_fh:rewardCash', value = -1},
	{trigger = 'utk_oh:rewardCash', value = -1},
	{trigger = 'wiz:reward', value = -1},
	{trigger = 'cmg2_animationsCarry:sync', value = -1},
}

TriggerConfig.BlacklistedEvents = {
   'chat:server:serverPSA',
   'kickAllPlayer',
   'esx_gopostaljob:pay',
   'esx_banksecurity:pay',
   'esx_slotmachine:sv:2',
   'lscustoms:payGarage',
   'vrp_slotmachine:server:2',
   'dmv:success',
   'esx_drugs:startHarvestCoke',
   'esx_drugs:startHarvestMeth',
   'esx_drugs:startHarvestWeed',
   'esx_drugs:startHarvestOpium',
   'KorioZ-PersonalMenu:Weapon_addAmmoToPedS',
   'KorioZ-PersonalMenu:Admin_BringS',
   'KorioZ-PersonalMenu:Admin_giveCash',
   'KorioZ-PersonalMenu:Admin_giveBank',
   'KorioZ-PersonalMenu:Admin_giveDirtyMoney',
   'KorioZ-PersonalMenu:Boss_promouvoirplayer',
   'KorioZ-PersonalMenu:Boss_destituerplayer',
   'KorioZ-PersonalMenu:Boss_recruterplayer',
   'KorioZ-PersonalMenu:Boss_virerplayer',
   "redst0nia:checking",
   "esx_mafiajob:confiscatePlayerItem",
   "lscustoms:payGarage",
   'parabas100k',
   'uzumbas100tane',
   'job:rev',
   'PGX:RevivePlayer',
   'gameCheck',
   'Anticheat:CheckStaffReturn',
   'anticheese:SetComponentStatus',
   'HCheat:TempDisableDetection',
   'BsCuff:Cuff696999',
   'police:cuffGranted',
   'mellotrainer:adminTempBan',
   'esx_truckerjob:pay',
   'AdminMenu:giveCash',
   'AdminMenu:giveBank',
   "cmg3_animations:cl_stop",
   "gameCheck",
   "Tem2LPs5Para5dCyjuHm87y2catFkMpV",
   "esx_pizza:pay",
   'AdminMenu:giveDirtyMoney',
   "paycheck:salary",
   "esx_pilot:success",
   "vrp_slotmachine:server:2",
   "OG_cuffs:cuffCheckNearest",
   "cuffServer",
   "cuffGranted",
   "esx_drugs:startHarvestWeed",
   "esx_drugs:startTransformWeed",
   "esx_drugs:startSellWeed",
   "esx_drugs:startHarvestCoke",
   "esx_drugs:startTransformCoke",
   "esx_drugs:startSellCoke",
   "esx_drugs:startHarvestMeth",
   "esx_drugs:startTransformMeth",
   "esx_drugs:startSellMeth",
   "esx_drugs:startHarvestOpium",
   "esx_drugs:startSellOpium",
   "esx_drugs:startTransformOpium",
   "esx_blanchisseur:startWhitening",
   "esx_drugs:stopHarvestCoke",
   "esx_drugs:stopTransformCoke",
   "esx_drugs:stopSellCoke",
   "esx_drugs:stopHarvestMeth",
   "esx_drugs:stopTransformMeth",
   "esx_drugs:stopSellMeth",
   "NCPP:RequestAuth",
   "esx_drugs:stopHarvestWeed",
   "esx_drugs:stopTransformWeed",
   "esx_drugs:stopSellWeed",
   "esx_drugs:stopHarvestOpium",
   "esx_drugs:stopTransformOpium",
   "esx_drugs:stopSellOpium",
   "esx_jobs:caution",
   "esx_tankerjob:pay",
   "esx_vehicletrunk:giveDirty",
   "esx_jobs:caution",
   "give_back",
   "esx_fueldelivery:pay",
   "esx_carthief:pay",
   "esx_godirtyjob:pay",
   "esx_pizza:pay",
   "esx_ranger:pay",
   "esx_truckerjob:pay",
   "AdminMenu:giveBank",
   "AdminMenu:giveCash",
   "esx_gopostaljob:pay",
   "esx_illegal_drugs:stopHarvestWeed",
   "esx_banksecurity:pay",
   "esx_slotmachine:sv:2",
   "esx_jail:sendToJail",
   "esx_jailer:sendToJail",
   "NB:recruterplayer",
   "js:jailuser",
   "gambling:spend",
   "AdminMenu:giveDirtyMoney",
   "truckerJob:success",
   "99kr-burglary:addMoney",
   "esx_jailer:unjailTime",
   "hentailover:xdlol",
   "antilynx8:anticheat",
   "antilynxr6:detection",
   "antilynx8r4a:anticheat",
   "antilynxr4:detect",
   "js:jailuser", 
   "ynx8:anticheat",
   "lester:vendita",
   "lynx8:anticheat",
   "adminmenu:allowall",
   "h:xd",
   "ljail:jailplayer",
   "adminmenu:setsalary",
   "adminmenu:cashoutall",
   "esx_drugs:pickedUpCannabis",
   "esx_drugs:processCannabis",
   "esx-qalle-hunting:reward",
   "esx-qalle-hunting:sell",
   "esx_mecanojob:onNPCJobCompleted",
   "BsCuff:Cuff696999",
   "veh_SR:CheckMoneyForVeh",
   "mellotrainer:adminTempBan",
   "mellotrainer:adminKick",
   "crown_xyz:getFuckedNigger",
   "esx:clientLog",
   "kashactersS:DeleteCharacter",
   "lscustoms:UpdateVeh",
   "esx_carthief:alertcops",
   "Banca:deposit",
   "esx_inventoryhud:openPlayerInventory",
   "NB:destituerplayer",
   "tm1_mafias:addMoney",
   "pop_transporte:paga",
   "tm1_mafias:addItem",
   "eden_garage:payhealth",
   "Banca:withdraw",
   'FaxDisVeh:CheckPermission:Return',
   'blacklist.setAdminPermissions',
   "HCheat:TempDisableDetection",
   "d0pamine_xyz:getFuckedNigger",
}     